# Generated by Django 5.0.1 on 2024-03-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army', '0004_store_percentage_store_price_and_quantity_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
