# Generated by Django 5.0.1 on 2024-03-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='price_and_quantity_total',
            field=models.IntegerField(default=0),
        ),
    ]
